make the "load docker image from cache" command fail if it can't find the cache file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,24 +10,25 @@ x-config:
       LOCAL_NAME: *name
       DEST_NAME: docker.io/hybsearch/hybsearch
   - &caches
-    docker-load: &cache-load-docker
+    - &cache-load-docker
       keys:
         - docker--{{ arch }}-{{ .Branch }}
         - docker--{{ arch }}
-    docker-save: &cache-save-docker
+    - &cache-save-docker
       key: docker--{{ arch }}-{{ .Branch }}-{{ .BuildNum }}
       paths:
         - /tmp/image.tar.gz
-    docker-load-cmd: &cmd-docker-load
+    - &cmd-docker-load
       name: 'Load from cache if possible'
       command: |
         if test -r /tmp/image.tar.gz; then
           echo "Loading from /tmp/image.tar.gz"
           docker load -qi /tmp/image.tar.gz
         else
-          echo "missing /tmp/image.tar.gz; continuing with build"
+          echo "missing /tmp/image.tar.gz; failing the build"
+          exit 1
         fi
-    docker-save-command: &cmd-docker-save
+    - &cmd-docker-save
       name: 'Dump image to cachable .tar.gz file'
       command: docker save "$LOCAL_NAME:$CIRCLE_SHA1" | pigz -9c > /tmp/image.tar.gz
 
